### PR TITLE
Updated for 0.16

### PR DESCRIPTION
**Pull request by gemurdock**
Just a simple change of version number.

### CODE REVIEW

**Comment by othyn** [comment]
Is this confirmed working on 0.16?

**Comment by gemurdock** [comment]
I have only test it a little, but yes it is working. On previous saved games it works and on new games it works just fine.

**Comment by othyn** [comment]
Cool, will merge

**Comment by othyn** [comment]
Updated and live, verified working. Thank you for your PR! I will get the others updated shortly.

**Pull request merged**
